#!/usr/bin/env python
# coding: utf-8

# ## Split function and while else 

# In[1]:


text="Welcome to my home"


# In[2]:


text.split()


# In[ ]:





# In[ ]:


# Split (separator, maxplit)


# In[3]:


text="I love python"


# In[4]:


text.split()


# In[ ]:





# In[7]:



x=input("enter three word message")


# In[8]:


x


# In[11]:


word1,word2,word3=x.split()

# the number of variables on left of assignment operator and number of values 
# generated by split() must be same


# In[12]:


print(word1)


# In[13]:


print(word2)


# In[14]:


print(word3)


# In[15]:


# Write a prigram that ask the user input 2 integers and add them 
# accept both number in single


# In[16]:


s=input("enter the roll no,name percentage")
roll,name,percentage=s.split()
print("roll no",roll)
print("name",name)
print("percentage",percentage)


# In[ ]:





# ## Example of max split

# In[25]:


shubham1="A,B,C,D,E,F"
print(shubham1.split(' ',4))


# In[23]:


s1="HI@HI@HI@HI@"
print(s1.split('@',2))


# In[24]:


s3=("One#two#three#four#five")
print(s3.split('#'))


# In[ ]:





# ## While loop

# In[26]:


i=1
while i<=10:
    print(i)
    i=i+1
print("Done")


# ## In while loop " Use of Break statement"  what break statment do

# In[27]:


i=1
while i<=10:
    if(i==5):
        break
    print(i)
    i=i+1
print("Done")


# In[29]:


i=1
while i<=10:
     
    print(i)
    
    i=i+1
    
print("Done")


# In[ ]:





# ## Write a program to wite a odd number only

# In[36]:


num=0

while num < 10:
    num=num+1
    
    if (num % 2) == 0:
        
        continue 
        
        print(num)


# In[ ]:





# In[38]:


i=0
while i < 9:
    i=i+1
    if i==3:
        continue
        print(i)


# In[ ]:





# In[39]:


i=0
while i < 10:
    i=i+1
    if (i%2!=0):
        pass
    else:
        print(i)


# In[42]:


i=0
while i < 9:
    i=i+1
    if i==3:
        pass
    
        print(i)


# In[54]:


my_list=["papaya","orange","mango","pineapple","graphs"]


# In[55]:


size=len(my_list)


# In[56]:


size


# In[59]:


my_list=["papaya","orange","pineapple","mango","graphs"]

size=len(my_list)

i=0
while i<size:
    if my_list[i] == "mango":
        print("mango found")
        break  
        i=i+1
        else:
    print("mango not found")
     


# ## Practice quetion looping statement : 
# 

# In[10]:


i=0
while i<4:
    i=i+1
    if(i%2!=0):
        continue
        print("hi",end="")
    else:
        print(i,end="")
        


# In[13]:


i=0
while i<4:
    i=i+1
    if(i%2!=0):
        break
        print("hi",end="")
    else:
        print(i,end="")
        


# In[14]:


## this topic is not covered yet

x = 123
for i in x:
    print(i)


# In[24]:


i = 1
while True:
      if i%2 == 0:
            break
        print(i,end="")
        i+ = 2


# In[25]:


x = "abcderf"
i = "i"
while i in x:
    print("i",end="")


# In[ ]:





# In[26]:


x = "abcderf"
i = "a"
while i in x:
    print("i",end="")


# In[29]:


## Slicer concept 

x = "abcderf"
i = "a"
while i in x:
    x = x[1:]
    print(i,end=" ")


# In[30]:


## Slicer concept 


x = "abcderf"
i = "c"
while i in x:
    x = x[1:]
    print(i,end=" ")


# ## Done 

# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:




